### ISSUE TITLE
About the sampling strategy when training

### ISSUE THREAD

**Issue by zhongyingji** [munjalbharti/Query-guided-End-to-End-Person-Search#2]
Hi, 
  I read the paper today and it is inspiring, i have got a problem about details, the paper says "for training, we consider all query-gallery image pairs for the CUHK-SYSU dataset". I have no idea what does it mean. Does it mean that for EVERY person, select all the frames which contain it, suppose N frame, and come up with N(N-1) pairs for this person?

**Comment by munjalbharti** [comment]
Hi,
Yes you are right.
