### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by huanglianghua** [munjalbharti/Query-guided-End-to-End-Person-Search#3]
Hi, thanks for your great work. I wonder when will the code be released. Thanks.

**Comment by munjalbharti** [comment]
Hi,
We apologize we can not make the code public due to company's regulations.  We would be happy to support you if you have questions for your own implementation.

**Comment by xuelimin** [comment]
I wonder to learn your code and do some research about query images, can you contract me ?

**Comment by munjalbharti** [comment]
Hi,
Yes sure. How should I contact you?

Regards
Bharti

**Comment by xuelimin** [comment]
hi:
   I am so happy you contract me! As I am a student from fudan university,china,,recently I want to add your query idea into OIM(Joint Detection and Identification Feature Learning for Person Search), but I can't get your code including sevearl loss as you designed in your paper, you can contract me with weixin(ID:xuemin-weixin, only used in china?) or email? I really want to learn your code as My first step in the person-search field。
------------------ 原始邮件 ------------------
发件人: "Bharti"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 凌晨1:46
收件人: "munjalbharti/Query-guided-End-to-End-Person-Search"<Query-guided-End-to-End-Person-Search@noreply.github.com>;
抄送: "达达"<929410161@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [munjalbharti/Query-guided-End-to-End-Person-Search] When willthe code be released? (#3)



Hi,
 Yes sure. How should I contact you?
 
 Regards
 Bharti

**Comment by munjalbharti** [comment]
Hi,
Email would be better. Please share you email id.

Regards
Bharti

**Comment by xuelimin** [comment]
Hi,
   My email is 929410161@qq.com 
Best regards 
Xuelimin


发自我的iPhone

------------------ Original ------------------

**Comment by loslorien** [comment]
Hi, 
I am a student of the Chinese University of Hong Kong(Shenzhen). I read your paper and find the idea of 'guided' is fantastic. I hope to add it in my research of crowd counting. Do you mind let me learn your code and do some research? Thanks.

**Comment by munjalbharti** [comment]
As I said before we can not make the code public. We would be happy to support you if you have questions for your own implementation.

**Comment by loslorien** [comment]
My re-implementation still cannot achieve the result reported in the paper. I think there is still some ambiguity in the QRPN parts. 1. I notice you do a ROI Pool before the FC1 layer and I hope to know whether I should give the gt_rois in this ROI Pool process. 2. I hope to know how to get the proposals of the lower branch in the Figure 2, which is that I should just use the re-weighted feature map to get the proposals or I should concatenate the proposals of the RPN and the QRPN. Thank you.

**Comment by munjalbharti** [comment]
Hi,
The ROI pool is applied after the BaseNet. For Query image, the roi pool is applied to query gt roi. For gallery image, it is applied to all selected rois/proposals.

To get the proposals of the gallery (lower branch), you need to do the following:

1. Get the output of RPN that takes the gallery features coming from BaseNet. RPN gives object probability and bounding box deltas for each anchor.
2. Get the output of QRPN (that re-weights the gallery feature, see Figure 4). QRPN gives query match probabilities for each anchor.
3.  Sum the two probabilities for each anchor (Object probability + Query match probability)
4. Then you apply the proposal layer like https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/rpn/proposal_layer.py passing the summed scores, and the deltas from RPN.

Regards

**Comment by loslorien** [comment]
Thank you so much. I will try it.

Best regards.
