### ISSUE TITLE
PRW evaluation

### ISSUE THREAD

**Issue by tyz1994** [munjalbharti/Query-guided-End-to-End-Person-Search#4]
I notice that in your prw_test.py, you didn't use camera id information for PRW. Did you treat the correct matches from the same camera as positive?  
 In this script, (https://github.com/liangzheng06/PRW-baseline/blob/master/baseline_dpm_bow_new.m ) images with the same ID and the same camera as the query are ignored during testing. 
Do you think it is necessary to ignore images with the same ID and same camera?

Best regards.

**Comment by munjalbharti** [comment]
Hi,
We evaluate on PRW  using the same evaluation as used by previous state-of-the-art work Mask-G [1], which considers images from same camera also. 
Ignoring images of same ID from same camera makes the evaluation harder.

[1] D. Chen, S. Zhang, W. Ouyang, J. Yang, and Y. Tai. Person search via a mask-guided two-stream cnn model. In The European Conference on Computer Vision (ECCV), 2018

**Comment by tyz1994** [comment]
Thanks for your reply. Looking forward to your new research!
