### ISSUE TITLE
Could you please explain some details?

### ISSUE THREAD

**Issue by asdfqwer2015** [munjalbharti/Query-guided-End-to-End-Person-Search#5]
Hi, munjalbharti:
  Thanks for your paper, it's very interesting.
  And could you please explain some details since you can't make your code public.
  a. how to do pre-training
  The backbone seems to unavailable to pre-train with imagenet due to shared attention struct(i.e. QSSE).
  Should I train it with re-id dataset from scratch?
  b. the performance gap in your implement between input cropped query image(i.e. x1y1x2y2 of query_img is [0, 0, w-1, h-1]) and input whole query image?
Thanks.

**Comment by munjalbharti** [comment]
Hi,
a.  As mentioned in paper, we use Detect+OIM model to pre-train QEEPS and not imagenet. The new layers  in QSSE are initialized using default initialization in pytorch. 
b. Using the cropped query image (and not the full query image), makes our model OIM+QRPN+QSimNet. The performance gap between this model and our final QEEPS (which considers full query image using QSSE) is 1.3pp mAP for gallery size 100. (83.1 Vs 84.4)

**Comment by asdfqwer2015** [comment]
Thanks for your detailed reply.
