### ISSUE TITLE
Can you share the feature of NEW baseline model?

### ISSUE THREAD

**Issue by daodaofr** [munjalbharti/Query-guided-End-to-End-Person-Search#6]
Great work. 
I notice that in your paper, you use an input image of size 900 instead of 600, the baseline OIM model achieves mAP 83.3 and top-1 84.2 on CUHK-SYSU.

Can you share the extracted features of this strong baseline? e.g., gallery_detections.pkl, gallery_features.pkl etc. I think this will greatly promote the advance of the this task.

Thanks.

**Comment by munjalbharti** [comment]
Hi,
We have made it available. Please look at OIM‡ folder.  

Regards, Bharti

**Comment by daodaofr** [comment]
Thanks @munjalbharti 

I try to achieve your strong baseline results using shuang's code https://github.com/ShuangLI59/person_search.
I change the input size to 900, and max size to 1500, but I only get mAP 63% and top-1 63%. Do you also use shuang's code?  Are there any other tricks you would like to share? 

Thanks

**Comment by munjalbharti** [comment]
Hi,
The features are not normalized. You need to normalize the gallery and probe features before taking the dot product (line 261) in psdb.py   

(https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py)

**Comment by daodaofr** [comment]
Thanks @munjalbharti 

Using your features, I have successfully reproduced your results with normalization. 
But when I train my own model, the results are lower. Are you will to also share the trained baseline model if you are using the same framework.

Thanks a lot.

**Comment by munjalbharti** [comment]
Hi,
You might need to change the anchor scales and ratios. Please look at the implementation details of our paper. We also augment the data by flipping.
